matrix:
  include:
  - language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - extra
      - build-tools-29.0.2
      - android-29
    script:
    - ionic cordova build android --prod --release -- -- --packageType=bundle
  - language: objective-c
    os: osx
    osx_image: xcode12.2
    script:
    - ionic cordova build ios --prod
  - language: node_js
    script:
    - ionic build --prod -- --base-href=/openlap/ --service-worker

before_install:
- nvm install 10

install:
- npm install -g cordova @ionic/cli
- npm install
